// react-client/src/components/AddTransaction.js
import React, { useState, useContext } from 'react'
import { GlobalContext } from '../context/GlobalState'

const AddTransaction = () => {
    const [text, settext] = useState('')
    const [amount, setAmount] = useState('')
    const { addTransaction } = useContext(GlobalContext)
    const newTrans = (e) => {
        e.preventDefault();
        const transaction = {id: Math.floor(Math.random() * 100000000), text, amount: +amount}
        addTransaction(transaction)
        setAmount('');
        settext('')
    }
    return (
        <div>
            <h3>Add new transaction</h3>
            <form onSubmit={newTrans}>
                <div className="form-control">
                <label htmlFor="text">Text</label>
                <input type="text" placeholder="Enter text..." value={text} onChange={(e) => settext(e.target.value)} />
                </div>
                <div className="form-control">
                <label htmlFor="amount">Amount <br />(negative - expense, positive - income)</label>
                <input type="number" placeholder="Enter amount..." value={amount} onChange={(e) => setAmount(e.target.value)} />
                </div>
                <button className="btn">Add transaction</button>
            </form>
        </div>
    )
}

export default AddTransaction

// vue-client/src/components/AddTransaction.vue
<template>
    <div>
        <h3>Add new transaction</h3>
        <form @submit.prevent="newTransaction">
            <div class="form-control">
            <label for="text">Text</label>
            <input type="text" placeholder="Enter text..." v-model="transaction.text" />
            </div>
            <div class="form-control">
            <label for="amount">Amount <br />(negative - expense, positive - income)</label>
            <input type="number" placeholder="Enter amount..." v-model="transaction.amount" />
            </div>
            <button class="btn">Add transaction</button>
        </form>
    </div>
</template>

<script>
import { mapActions } from 'vuex'
export default {
    data() {
        return {
            transaction: {
                text: '',
                amount: ''
            }
        }
    },
    methods: {
        ...mapActions(['addTransaction']),
        newTransaction() {
            this.transaction.amount = +this.transaction.amount
            this.addTransaction(this.transaction)
         },
    },
}
</script>
