// react-client/src/components/Balance.js
import React, { useContext } from 'react'
import { GlobalContext } from '../context/GlobalState'

const Balance = () => {

    const { transactions } = useContext(GlobalContext)
    const amounts = transactions.map(transaction => transaction.amount);
    const total = amounts.reduce((acc, item) => (acc += item), 0).toFixed(2);

    return (
        <>
            <h4>Your Balance</h4>
            <h1>${total}</h1>
        </>
    )
}

export default Balance

// vue-client/src/components/Balance.vue
<template>
    <div>
        <h4>Your Balance</h4>
        <h1>${{total}}</h1>
    </div>
</template>

<script>
export default {
    computed: {
        total() {
            const transactions = this.$store.state.transactions
            const amount = transactions.map(t => t.amount)
            return amount.reduce((acc,item) => (acc += item), 0).toFixed(2)
        }
    }
}
</script>
